[parameters]
head_width = 30
head_height = 10
cell_width = 20
cell_height = 8
project_spacing_width = 0
project_spacing_height = 0
shape_scale_width = 0.0
shape_scale_height = 0.0
group_spacing_height = 2


