[parameters]
head_width = 20
head_height = 8
cell_width = 20
cell_height = 5
project_spacing_width = 0
project_spacing_height = 0
shape_scale_width = 0.0
shape_scale_height = 0.0
group_spacing_height = 2

[line_style]
fill = "green"
stroke = "black"
stroke_width = 1
stroke_opacity = 1.0
fill_opacity = 0.5
#stroke_linecap = None
#stroke_linejoin = None
#stroke_dasharray = None
#stroke_dashoffset = None
#transform = None

[path_style]
fill = "green"
stroke = "black"
stroke_width = 1
stroke_opacity = 1.0
fill_opacity = 0.5
#stroke_linecap = None
#stroke_linejoin = None
#stroke_dasharray = None
#stroke_dashoffset = None
#transform = None

[polygon_style]
fill = "green"
stroke = "blue"
stroke_width = 1
stroke_opacity = 1.0
fill_opacity = 0.5
#transform = None

[rectangle_style]
fill = "white"
stroke = "black"
stroke_width = 1
stroke_opacity = 1.0
fill_opacity = 0.5
#rx = None,
#ry = None,
#transform = None,

[text_style]
font_family = "Arial"
font_size = 7
text_anchor = "middle"
fill = "black"
font_weight = "normal"
